using System.Collections;
using System.Globalization;
using Game.Core.Bootstrap;
using Game.Core.Components.Base2D;
using Game.Core.Services.Scene;
using Game.Core.Utils;
using Game.Features.Portals.Common;
using UnityEditor;
using UnityEngine;
using UnityEngine.Events;

namespace Game.Features.Portals.Entrance {
    /// <summary>
    /// A scene entrance that transitions the player to another entrance (in this or another scene)
    /// the moment the player enters its trigger collider. Unlike Door, entrances are
    /// not interactable — there is no button press, no open/close animation. Entrances only connect
    /// to other entrances (the link drawer filters the dropdown by kind, validator enforces it too).
    ///
    /// When <see cref="backSpawnPoint"/> is set, the travel becomes a cinematic walk:
    /// on the source side the hero walks INTO the portal (opposite of <see cref="Facing2D"/> direction)
    /// until exiting the collider; on the destination side the hero spawns at the destination's
    /// back-spawn (typically offscreen) and walks OUT toward the destination's entry point.
    /// Without a back-spawn, the entrance falls back to a Door-style instant teleport.
    /// </summary>
    [RequireComponent(typeof(Collider2D))]
    [RequireComponent(typeof(Facing2D))]
    public sealed class Entrance : MonoBehaviour, IPortal {
        private const string PlayerTag = "Player";
        private const float CinematicWalkTimeoutSeconds = 5f;
        private const float CinematicReachThreshold = 0.15f;

        [SerializeField, HideInInspector]
        private string entranceId;

        [Tooltip("Destination scene and entrance the player is sent to when entering this trigger. " +
                 "Entrances can only target other entrances.")]
        [SerializeField]
        private PortalLink link;

        [Tooltip("World position the player is teleported to when arriving at this entrance. " +
                 "Place it OUTSIDE the trigger collider so the player does not immediately re-trigger travel. " +
                 "If left empty, the entrance's own transform position is used.")]
        [SerializeField]
        private Transform entryPoint;

        [Tooltip("Optional offscreen position behind the portal. When set, arrivals spawn here and " +
                 "the hero cinematically walks to EntryPoint while the screen fades in. " +
                 "Leaving it empty disables the walk-in/walk-out cinematic and falls back to an " +
                 "instant teleport like Door.")]
        [SerializeField]
        private Transform backSpawnPoint;

        [Tooltip("Invoked after the player has finished traveling to this entrance. " +
                 "Hook audio cues or other arrival effects here.")]
        [SerializeField]
        private UnityEvent onEntered;

        private Facing2D facing;
        private bool playerExitedCollider;

        /// <summary>
        /// Entrance identifier. Stored as a numeric string ("1", "2", ...) generated by per-scene autoincrement.
        /// Must be unique within a scene. Not editable directly; use the editor "Change ID" action.
        /// </summary>
        public string EntranceId => entranceId;

        /// <summary>
        /// Destination link for this entrance. Points to another Entrance (filtered by kind in the link drawer).
        /// </summary>
        public PortalLink Link => link;

        string IPortal.Id => entranceId;
        SceneReference IPortal.TargetScene => link.TargetScene;
        string IPortal.TargetId => link.TargetId;

        public Vector3 GetEntryPosition() {
            if (entryPoint != null) {
                return entryPoint.position;
            }

            return transform.position;
        }

        /// <summary>
        /// Optional offscreen spawn position used on the destination side of a cinematic travel.
        /// Null when the entrance is configured for instant teleport.
        /// </summary>
        public Vector3? GetBackSpawnPosition() {
            return backSpawnPoint != null ? backSpawnPoint.position : (Vector3?)null;
        }

        /// <summary>
        /// Invoked after the player has arrived at this entrance. Wired by designers when audio or
        /// other side effects must play on arrival.
        /// </summary>
        public void NotifyEntered() {
            onEntered?.Invoke();
        }

        private void Awake() {
            facing = GetComponent<Facing2D>();
        }

        private void OnTriggerEnter2D(Collider2D other) {
            if (!other.CompareTag(PlayerTag)) {
                return;
            }

            // Suppress re-triggering while a travel is in progress (e.g. player passes through the
            // destination collider during the walk-out cinematic).
            if (PortalTravelService.IsTraveling) {
                return;
            }

            var hooks = backSpawnPoint != null ? BuildCinematicHooks() : null;
            PortalTravelService.Travel(this, PortalUtils.FindPortalByIdInScene<Entrance>, hooks);
        }

        private void OnTriggerExit2D(Collider2D other) {
            if (other.CompareTag(PlayerTag)) {
                playerExitedCollider = true;
            }
        }

        private PortalTravelHooks BuildCinematicHooks() {
            return new PortalTravelHooks {
                BeforeFadeOut = WalkIntoPortalCoroutine,
                ResolveSpawnPosition = ResolveDestinationSpawn,
                AfterArrival = WalkOutOfPortalCoroutine,
            };
        }

        private static Vector3 ResolveDestinationSpawn(IPortal target) {
            // The destination entrance might have its own back-spawn (preferred), otherwise just
            // teleport to its entry point and skip the walk-out animation.
            if (target is Entrance destEntrance) {
                var back = destEntrance.GetBackSpawnPosition();
                if (back.HasValue) {
                    return back.Value;
                }
            }

            return target.GetEntryPosition();
        }

        private IEnumerator WalkIntoPortalCoroutine() {
            var hero = G.Hero.Controller;
            if (hero == null || facing == null) {
                yield break;
            }

            // Walk in the opposite direction of the portal facing — that's the direction "into" the portal.
            // CheckHorizontalMovement will also flip hero facing to match the walk dir.
            playerExitedCollider = false;
            hero.BeginScriptedWalk(-facing.DirSign);

            var elapsed = 0f;
            while (!playerExitedCollider && elapsed < CinematicWalkTimeoutSeconds) {
                elapsed += Time.deltaTime;
                yield return null;
            }

            hero.EndScriptedWalk();
        }

        private static IEnumerator WalkOutOfPortalCoroutine(IPortal target) {
            var dest = target as Entrance;
            var hero = G.Hero.Controller;
            if (dest == null || hero == null || dest.facing == null) {
                yield break;
            }

            // Walk out in the destination facing direction toward its entry point.
            var walkDir = dest.facing.DirSign;
            hero.BeginScriptedWalk(walkDir);

            var entryX = dest.GetEntryPosition().x;
            var elapsed = 0f;

            while (elapsed < CinematicWalkTimeoutSeconds) {
                var heroX = hero.transform.position.x;
                // Walking right: stop once we passed (or reached) entryX. Walking left: mirror.
                if (walkDir > 0 && heroX >= entryX - CinematicReachThreshold) {
                    break;
                }

                if (walkDir < 0 && heroX <= entryX + CinematicReachThreshold) {
                    break;
                }

                elapsed += Time.deltaTime;
                yield return null;
            }

            hero.EndScriptedWalk();
        }

        private static readonly Color GizmoSpawnColor = new Color(1f, 0.85f, 0f, 0.9f);
        private static readonly Color GizmoBackSpawnColor = new Color(0.4f, 0.6f, 1f, 0.9f);
        private static readonly Color GizmoLinkColor = new Color(0f, 1f, 0.4f, 0.7f);
        private const float GizmoCrossSceneHintLength = 1.5f;

        private void OnDrawGizmos() {
            var center = GetColliderCenter();
            var spawnPos = GetEntryPosition();

            // Front entry marker (yellow): where the player ends up after walking out.
            Gizmos.color = GizmoSpawnColor;
            Gizmos.DrawSphere(spawnPos, 0.12f);

            // Back spawn marker (blue): where the player materializes on arrival before walking out.
            if (backSpawnPoint != null) {
                Gizmos.color = GizmoBackSpawnColor;
                Gizmos.DrawWireSphere(backSpawnPoint.position, 0.12f);
                Gizmos.DrawLine(backSpawnPoint.position, spawnPos);
            }

            if (string.IsNullOrEmpty(link.TargetId)) {
                return;
            }

            // Connection hint from the collider center: line to the target collider in the same scene,
            // or a short upward stub for cross-scene targets (full label shown when selected).
            Gizmos.color = GizmoLinkColor;

            if (link.TargetScene.ScenePath == gameObject.scene.path) {
                var targetEntrance = PortalUtils.FindPortalByIdInScene<Entrance>(gameObject.scene, link.TargetId);
                if (targetEntrance != null) {
                    Gizmos.DrawLine(center, targetEntrance.GetColliderCenter());
                }
            } else {
                Gizmos.DrawLine(center, center + (Vector3.up * GizmoCrossSceneHintLength));
            }
        }

        private void OnDrawGizmosSelected() {
            if (string.IsNullOrEmpty(link.TargetId)) {
                return;
            }

#if UNITY_EDITOR
            var center = GetColliderCenter();
            var labelPos = center + (Vector3.up * GizmoCrossSceneHintLength);

            string text;
            var targetLabel = "#" + link.TargetId;
            if (link.TargetScene.ScenePath == gameObject.scene.path) {
                text = "→ " + targetLabel;
            } else {
                var sceneName = link.TargetScene.GetSceneName();
                if (string.IsNullOrWhiteSpace(sceneName)) {
                    return;
                }

                text = "→ " + sceneName + "\n" + targetLabel;
            }

            var style = PortalGizmoLabelStyle.Get();
            var content = new GUIContent(text);
            var size = style.CalcSize(content);
            var padding = new Vector2(12f, 8f);

            var guiPoint = HandleUtility.WorldToGUIPoint(labelPos);

            var rect = new Rect(
                guiPoint.x - (size.x + padding.x) * 0.5f,
                guiPoint.y - (size.y + padding.y) * 0.5f,
                size.x + padding.x,
                size.y + padding.y
            );

            Handles.BeginGUI();

            var labelRect = new Rect(
                rect.x + padding.x * 0.5f,
                rect.y + padding.y * 0.5f,
                rect.width - padding.x,
                rect.height - padding.y
            );

            EditorGUI.LabelField(labelRect, text, style);
            Handles.EndGUI();
#endif
        }

        private Vector3 GetColliderCenter() {
            var col = GetComponent<Collider2D>();
            if (col != null) {
                return col.bounds.center;
            }

            return transform.position;
        }

#if UNITY_EDITOR
        private void OnValidate() {
            if (Application.isPlaying) {
                return;
            }

            // Prefab asset itself never carries a per-scene id; clear so it does not propagate to instances.
            if (PrefabUtility.IsPartOfPrefabAsset(this)) {
                if (!string.IsNullOrEmpty(entranceId)) {
                    entranceId = string.Empty;
                    EditorUtility.SetDirty(this);
                }

                return;
            }

            // Prefab instances inherit the source's id (empty); reassign.
            var source = PrefabUtility.GetCorrespondingObjectFromSource(this) as Entrance;
            var isInheritedFromPrefab = source != null && string.Equals(entranceId, source.entranceId, System.StringComparison.Ordinal);

            if (string.IsNullOrEmpty(entranceId) || isInheritedFromPrefab) {
                entranceId = NextFreeIdInScene().ToString(CultureInfo.InvariantCulture);
                EditorUtility.SetDirty(this);
            }
        }

        /// <summary>
        /// Returns max numeric id of all Entrances in this scene + 1, ignoring this instance and non-numeric ids.
        /// </summary>
        private int NextFreeIdInScene() {
            var entrances = PortalUtils.GetPortalsInScene<Entrance>(gameObject.scene);
            int max = 0;
            for (var i = 0; i < entrances.Count; i++) {
                var other = entrances[i];
                if (other == null || other == this) {
                    continue;
                }

                if (IdUtils.TryParsePortalId(other.entranceId, out var otherId) && otherId > max) {
                    max = otherId;
                }
            }

            return max + 1;
        }

        public void EditorSetEntranceId(string newId) {
            entranceId = newId;
        }
#endif
    }
}
