using System.Globalization;
using Game.Core.Components.Interaction;
using Game.Core.Services.Scene;
using Game.Core.Utils;
using Game.Features.Portals.Common;
using UnityEditor;
using UnityEngine;
using UnityEngine.Events;

namespace Game.Features.Portals.Doors {
    /// <summary>
    /// A scene door that transitions the player to another door when interacted with.
    /// The door uses a per-scene autoincrement id stored as a numeric string ("1", "2", ...).
    /// </summary>
    public sealed class Door : InteractableBase, IPortal {
        [SerializeField, HideInInspector]
        private string doorId;

        [SerializeField]
        private PortalLink link;

        [SerializeField]
        private Transform entryPoint;

        [SerializeField]
        private UnityEvent onEntered;

        /// <summary>
        /// Door identifier. Stored as a numeric string ("1", "2", ...) generated by per-scene autoincrement.
        /// Must be unique within a scene. Not editable directly; use the editor "Change ID" action.
        /// </summary>
        public string DoorId => doorId;

        /// <summary>
        /// Destination link for this door. Points to another Door (filtered by kind in the link drawer).
        /// </summary>
        public PortalLink Link => link;

        string IPortal.Id => doorId;
        SceneReference IPortal.TargetScene => link.TargetScene;
        string IPortal.TargetId => link.TargetId;

        public Vector3 GetEntryPosition() {
            if (entryPoint != null) {
                return entryPoint.position;
            }

            return transform.position;
        }

        /// <summary>
        /// Immediately loads target scene and teleports player there.
        /// Called by the door prefab UnityEvent on interact.
        /// </summary>
        public void TravelToTarget() {
            PortalTravelService.Travel(this, PortalUtils.FindPortalByIdInScene<Door>);
        }

        /// <summary>
        /// Disables player control and damage intake before the door opening animation starts.
        /// Wire this before door opening events so the transition lock begins on the first interact frame.
        /// </summary>
        public void BeginTravelTransition() {
            var hero = Game.Core.Bootstrap.G.Hero.Controller;
            if (hero == null) {
                return;
            }

            hero.SetCanTakeDamage(false);
            hero.SetControlsEnabled(false);
        }

        /// <summary>
        /// Call this method from outer handlers when player has entered the door (close animation will be played).
        /// </summary>
        public void NotifyEntered() {
            onEntered?.Invoke();
        }

        private void OnDrawGizmos() {
            if (entryPoint == null) {
                return;
            }

            if (string.IsNullOrEmpty(link.TargetId)) {
                return;
            }

            Gizmos.color = new Color(0, 0, 1, 0.7f);
            var pos = entryPoint.transform.position;

            Gizmos.DrawSphere(pos, 0.1f);

            if (link.TargetScene.ScenePath == gameObject.scene.path) {
                var targetDoor = PortalUtils.FindPortalByIdInScene<Door>(gameObject.scene, link.TargetId);
                if (targetDoor != null && targetDoor.entryPoint != null) {
                    Gizmos.DrawLine(pos, targetDoor.entryPoint.transform.position);
                }
            }
        }

        private void OnDrawGizmosSelected() {
            if (entryPoint == null) {
                return;
            }

            if (string.IsNullOrEmpty(link.TargetId)) {
                return;
            }

            Gizmos.color = new Color(0, 0, 1, 0.7f);
            var pos = entryPoint.transform.position;

            if (link.TargetScene.ScenePath != gameObject.scene.path) {
                var len = 1.5f;
                var upPos = pos + (Vector3.up * len);
                Gizmos.DrawLine(pos, upPos);

#if UNITY_EDITOR
                var sceneName = link.TargetScene.GetSceneName();
                if (!string.IsNullOrWhiteSpace(sceneName)) {
                    var text = sceneName + "\n#" + link.TargetId;

                    var style = PortalGizmoLabelStyle.Get();

                    var content = new GUIContent(text);
                    var size = style.CalcSize(content);
                    var padding = new Vector2(12f, 8f);

                    var guiPoint = HandleUtility.WorldToGUIPoint(upPos);

                    var rect = new Rect(
                        guiPoint.x - (size.x + padding.x) * 0.5f,
                        guiPoint.y - (size.y + padding.y) * 0.5f,
                        size.x + padding.x,
                        size.y + padding.y
                    );

                    Handles.BeginGUI();

                    var labelRect = new Rect(
                        rect.x + padding.x * 0.5f,
                        rect.y + padding.y * 0.5f,
                        rect.width - padding.x,
                        rect.height - padding.y
                    );

                    EditorGUI.LabelField(labelRect, text, style);
                    Handles.EndGUI();
                }
#endif
            }
        }

#if UNITY_EDITOR
        private void OnValidate() {
            if (Application.isPlaying) {
                return;
            }

            // Prefab asset itself never carries a per-scene id; clear so it does not propagate to instances.
            if (PrefabUtility.IsPartOfPrefabAsset(this)) {
                if (!string.IsNullOrEmpty(doorId)) {
                    doorId = string.Empty;
                    EditorUtility.SetDirty(this);
                }

                return;
            }

            // Prefab instances inherit the source's id (empty); reassign.
            var source = PrefabUtility.GetCorrespondingObjectFromSource(this) as Door;
            var isInheritedFromPrefab = source != null && string.Equals(doorId, source.doorId, System.StringComparison.Ordinal);

            if (string.IsNullOrEmpty(doorId) || isInheritedFromPrefab) {
                doorId = NextFreeIdInScene().ToString(CultureInfo.InvariantCulture);
                EditorUtility.SetDirty(this);
            }
        }

        /// <summary>
        /// Returns max numeric id of all Doors in this scene + 1, ignoring this instance and non-numeric ids.
        /// </summary>
        private int NextFreeIdInScene() {
            var doors = PortalUtils.GetPortalsInScene<Door>(gameObject.scene);
            int max = 0;
            for (var i = 0; i < doors.Count; i++) {
                var other = doors[i];
                if (other == null || other == this) {
                    continue;
                }

                if (IdUtils.TryParsePortalId(other.doorId, out var otherId) && otherId > max) {
                    max = otherId;
                }
            }

            return max + 1;
        }

        public void EditorSetDoorId(string newId) {
            doorId = newId;
        }
#endif
    }
}
